In [1]:
import requests
import zipfile
import io
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [3]:
#source: https://lvr.land.moi.gov.tw/

# outdated link
# r= requests.get('https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=19059799-9436-4D7D-8C5E-90F1A9CE82DA', stream=True)

r = requests.get('https://plvr.land.moi.gov.tw/DownloadHistory?type=history&fileName=20251201', stream=True)

r.raise_for_status()

In [4]:
with zipfile.ZipFile(io.BytesIO(r.content)) as z:
    print("files: ", z.namelist())

    target_file = 'a_lvr_land_a.csv'
    with z.open(target_file) as f_in:
        df = pd.read_csv(f_in)

files:  ['c_lvr_land_a.txt', 'c_lvr_land_a.csv', 'c_lvr_land_a.xml', 'c_lvr_land_a.xls', 'c_lvr_land_a_build.txt', 'c_lvr_land_a_build.csv', 'c_lvr_land_a_build.xml', 'c_lvr_land_a_land.txt', 'c_lvr_land_a_land.csv', 'c_lvr_land_a_land.xml', 'c_lvr_land_a_park.txt', 'c_lvr_land_a_park.csv', 'c_lvr_land_a_park.xml', 'c_lvr_land_b.txt', 'c_lvr_land_b.csv', 'c_lvr_land_b.xml', 'c_lvr_land_b.xls', 'c_lvr_land_b_land.txt', 'c_lvr_land_b_land.csv', 'c_lvr_land_b_land.xml', 'c_lvr_land_b_park.txt', 'c_lvr_land_b_park.csv', 'c_lvr_land_b_park.xml', 'c_lvr_land_c.txt', 'c_lvr_land_c.csv', 'c_lvr_land_c.xml', 'c_lvr_land_c.xls', 'c_lvr_land_c_build.txt', 'c_lvr_land_c_build.csv', 'c_lvr_land_c_build.xml', 'c_lvr_land_c_land.txt', 'c_lvr_land_c_land.csv', 'c_lvr_land_c_land.xml', 'c_lvr_land_c_park.txt', 'c_lvr_land_c_park.csv', 'c_lvr_land_c_park.xml', 'a_lvr_land_a.txt', 'a_lvr_land_a.csv', 'a_lvr_land_a.xml', 'a_lvr_land_a.xls', 'a_lvr_land_a_build.txt', 'a_lvr_land_a_build.csv', 'a_lvr_land_a_build.xml', 'a_lvr_land_a_land.txt', 'a_lvr_land_a_land.csv', 'a_lvr_land_a_land.xml', 'a_lvr_land_a_park.txt', 'a_lvr_land_a_park.csv', 'a_lvr_land_a_park.xml', 'a_lvr_land_b.txt', 'a_lvr_land_b.csv', 'a_lvr_land_b.xml', 'a_lvr_land_b.xls', 'a_lvr_land_b_land.txt', 'a_lvr_land_b_land.csv', 'a_lvr_land_b_land.xml', 'a_lvr_land_b_park.txt', 'a_lvr_land_b_park.csv', 'a_lvr_land_b_park.xml', 'a_lvr_land_c.txt', 'a_lvr_land_c.csv', 'a_lvr_land_c.xml', 'a_lvr_land_c.xls', 'a_lvr_land_c_build.txt', 'a_lvr_land_c_build.csv', 'a_lvr_land_c_build.xml', 'a_lvr_land_c_land.txt', 'a_lvr_land_c_land.csv', 'a_lvr_land_c_land.xml', 'a_lvr_land_c_park.txt', 'a_lvr_land_c_park.csv', 'a_lvr_land_c_park.xml', 'f_lvr_land_a.txt', 'f_lvr_land_a.csv', 'f_lvr_land_a.xml', 'f_lvr_land_a.xls', 'f_lvr_land_a_build.txt', 'f_lvr_land_a_build.csv', 'f_lvr_land_a_build.xml', 'f_lvr_land_a_land.txt', 'f_lvr_land_a_land.csv', 'f_lvr_land_a_land.xml', 'f_lvr_land_a_park.txt', 'f_lvr_land_a_park.csv', 'f_lvr_land_a_park.xml', 'f_lvr_land_b.txt', 'f_lvr_land_b.csv', 'f_lvr_land_b.xml', 'f_lvr_land_b.xls', 'f_lvr_land_b_land.txt', 'f_lvr_land_b_land.csv', 'f_lvr_land_b_land.xml', 'f_lvr_land_b_park.txt', 'f_lvr_land_b_park.csv', 'f_lvr_land_b_park.xml', 'f_lvr_land_c.txt', 'f_lvr_land_c.csv', 'f_lvr_land_c.xml', 'f_lvr_land_c.xls', 'f_lvr_land_c_build.txt', 'f_lvr_land_c_build.csv', 'f_lvr_land_c_build.xml', 'f_lvr_land_c_land.txt', 'f_lvr_land_c_land.csv', 'f_lvr_land_c_land.xml', 'f_lvr_land_c_park.txt', 'f_lvr_land_c_park.csv', 'f_lvr_land_c_park.xml', 'h_lvr_land_a.txt', 'h_lvr_land_a.csv', 'h_lvr_land_a.xml', 'h_lvr_land_a.xls', 'h_lvr_land_a_build.txt', 'h_lvr_land_a_build.csv', 'h_lvr_land_a_build.xml', 'h_lvr_land_a_land.txt', 'h_lvr_land_a_land.csv', 'h_lvr_land_a_land.xml', 'h_lvr_land_a_park.txt', 'h_lvr_land_a_park.csv', 'h_lvr_land_a_park.xml', 'h_lvr_land_b.txt', 'h_lvr_land_b.csv', 'h_lvr_land_b.xml', 'h_lvr_land_b.xls', 'h_lvr_land_b_land.txt', 'h_lvr_land_b_land.csv', 'h_lvr_land_b_land.xml', 'h_lvr_land_b_park.txt', 'h_lvr_land_b_park.csv', 'h_lvr_land_b_park.xml', 'h_lvr_land_c.txt', 'h_lvr_land_c.csv', 'h_lvr_land_c.xml', 'h_lvr_land_c.xls', 'h_lvr_land_c_build.txt', 'h_lvr_land_c_build.csv', 'h_lvr_land_c_build.xml', 'h_lvr_land_c_land.txt', 'h_lvr_land_c_land.csv', 'h_lvr_land_c_land.xml', 'h_lvr_land_c_park.txt', 'h_lvr_land_c_park.csv', 'h_lvr_land_c_park.xml', 'o_lvr_land_a.txt', 'o_lvr_land_a.csv', 'o_lvr_land_a.xml', 'o_lvr_land_a.xls', 'o_lvr_land_a_build.txt', 'o_lvr_land_a_build.csv', 'o_lvr_land_a_build.xml', 'o_lvr_land_a_land.txt', 'o_lvr_land_a_land.csv', 'o_lvr_land_a_land.xml', 'o_lvr_land_a_park.txt', 'o_lvr_land_a_park.csv', 'o_lvr_land_a_park.xml', 'o_lvr_land_b.txt', 'o_lvr_land_b.csv', 'o_lvr_land_b.xml', 'o_lvr_land_b.xls', 'o_lvr_land_b_land.txt', 'o_lvr_land_b_land.csv', 'o_lvr_land_b_land.xml', 'o_lvr_land_b_park.txt', 'o_lvr_land_b_park.csv', 'o_lvr_land_b_park.xml', 'o_lvr_land_c.txt', 'o_lvr_land_c.csv', 'o_lvr_land_c.xml', 'o_lvr_land_c.xls', 'o_lvr_land_c_build.txt', 'o_lvr_land_c_build.csv', 'o_lvr_land_c_build.xml', 'o_lvr_land_c_park.txt', 'o_lvr_land_c_park.csv', 'o_lvr_land_c_park.xml', 'j_lvr_land_a.txt', 'j_lvr_land_a.csv', 'j_lvr_land_a.xml', 'j_lvr_land_a.xls', 'j_lvr_land_a_build.txt', 'j_lvr_land_a_build.csv', 'j_lvr_land_a_build.xml', 'j_lvr_land_a_land.txt', 'j_lvr_land_a_land.csv', 'j_lvr_land_a_land.xml', 'j_lvr_land_a_park.txt', 'j_lvr_land_a_park.csv', 'j_lvr_land_a_park.xml', 'j_lvr_land_b.txt', 'j_lvr_land_b.csv', 'j_lvr_land_b.xml', 'j_lvr_land_b.xls', 'j_lvr_land_b_land.txt', 'j_lvr_land_b_land.csv', 'j_lvr_land_b_land.xml', 'j_lvr_land_b_park.txt', 'j_lvr_land_b_park.csv', 'j_lvr_land_b_park.xml', 'j_lvr_land_c.txt', 'j_lvr_land_c.csv', 'j_lvr_land_c.xml', 'j_lvr_land_c.xls', 'j_lvr_land_c_build.txt', 'j_lvr_land_c_build.csv', 'j_lvr_land_c_build.xml', 'j_lvr_land_c_land.txt', 'j_lvr_land_c_land.csv', 'j_lvr_land_c_land.xml', 'j_lvr_land_c_park.txt', 'j_lvr_land_c_park.csv', 'j_lvr_land_c_park.xml', 'k_lvr_land_a.txt', 'k_lvr_land_a.csv', 'k_lvr_land_a.xml', 'k_lvr_land_a.xls', 'k_lvr_land_a_build.txt', 'k_lvr_land_a_build.csv', 'k_lvr_land_a_build.xml', 'k_lvr_land_a_land.txt', 'k_lvr_land_a_land.csv', 'k_lvr_land_a_land.xml', 'k_lvr_land_a_park.txt', 'k_lvr_land_a_park.csv', 'k_lvr_land_a_park.xml', 'k_lvr_land_b.txt', 'k_lvr_land_b.csv', 'k_lvr_land_b.xml', 'k_lvr_land_b.xls', 'k_lvr_land_b_land.txt', 'k_lvr_land_b_land.csv', 'k_lvr_land_b_land.xml', 'k_lvr_land_b_park.txt', 'k_lvr_land_b_park.csv', 'k_lvr_land_b_park.xml', 'k_lvr_land_c.txt', 'k_lvr_land_c.csv', 'k_lvr_land_c.xml', 'k_lvr_land_c.xls', 'k_lvr_land_c_build.txt', 'k_lvr_land_c_build.csv', 'k_lvr_land_c_build.xml', 'k_lvr_land_c_park.txt', 'k_lvr_land_c_park.csv', 'k_lvr_land_c_park.xml', 'b_lvr_land_a.txt', 'b_lvr_land_a.csv', 'b_lvr_land_a.xml', 'b_lvr_land_a.xls', 'b_lvr_land_a_build.txt', 'b_lvr_land_a_build.csv', 'b_lvr_land_a_build.xml', 'b_lvr_land_a_land.txt', 'b_lvr_land_a_land.csv', 'b_lvr_land_a_land.xml', 'b_lvr_land_a_park.txt', 'b_lvr_land_a_park.csv', 'b_lvr_land_a_park.xml', 'b_lvr_land_b.txt', 'b_lvr_land_b.csv', 'b_lvr_land_b.xml', 'b_lvr_land_b.xls', 'b_lvr_land_b_land.txt', 'b_lvr_land_b_land.csv', 'b_lvr_land_b_land.xml', 'b_lvr_land_b_park.txt', 'b_lvr_land_b_park.csv', 'b_lvr_land_b_park.xml', 'b_lvr_land_c.txt', 'b_lvr_land_c.csv', 'b_lvr_land_c.xml', 'b_lvr_land_c.xls', 'b_lvr_land_c_build.txt', 'b_lvr_land_c_build.csv', 'b_lvr_land_c_build.xml', 'b_lvr_land_c_land.txt', 'b_lvr_land_c_land.csv', 'b_lvr_land_c_land.xml', 'b_lvr_land_c_park.txt', 'b_lvr_land_c_park.csv', 'b_lvr_land_c_park.xml', 'm_lvr_land_a.txt', 'm_lvr_land_a.csv', 'm_lvr_land_a.xml', 'm_lvr_land_a.xls', 'm_lvr_land_a_build.txt', 'm_lvr_land_a_build.csv', 'm_lvr_land_a_build.xml', 'm_lvr_land_a_land.txt', 'm_lvr_land_a_land.csv', 'm_lvr_land_a_land.xml', 'm_lvr_land_a_park.txt', 'm_lvr_land_a_park.csv', 'm_lvr_land_a_park.xml', 'm_lvr_land_b.txt', 'm_lvr_land_b.csv', 'm_lvr_land_b.xml', 'm_lvr_land_b.xls', 'm_lvr_land_b_land.txt', 'm_lvr_land_b_land.csv', 'm_lvr_land_b_land.xml', 'm_lvr_land_b_park.txt', 'm_lvr_land_b_park.csv', 'm_lvr_land_b_park.xml', 'm_lvr_land_c.txt', 'm_lvr_land_c.csv', 'm_lvr_land_c.xml', 'm_lvr_land_c.xls', 'm_lvr_land_c_build.txt', 'm_lvr_land_c_build.csv', 'm_lvr_land_c_build.xml', 'n_lvr_land_a.txt', 'n_lvr_land_a.csv', 'n_lvr_land_a.xml', 'n_lvr_land_a.xls', 'n_lvr_land_a_build.txt', 'n_lvr_land_a_build.csv', 'n_lvr_land_a_build.xml', 'n_lvr_land_a_land.txt', 'n_lvr_land_a_land.csv', 'n_lvr_land_a_land.xml', 'n_lvr_land_a_park.txt', 'n_lvr_land_a_park.csv', 'n_lvr_land_a_park.xml', 'n_lvr_land_b.txt', 'n_lvr_land_b.csv', 'n_lvr_land_b.xml', 'n_lvr_land_b.xls', 'n_lvr_land_b_land.txt', 'n_lvr_land_b_land.csv', 'n_lvr_land_b_land.xml', 'n_lvr_land_b_park.txt', 'n_lvr_land_b_park.csv', 'n_lvr_land_b_park.xml', 'n_lvr_land_c.txt', 'n_lvr_land_c.csv', 'n_lvr_land_c.xml', 'n_lvr_land_c.xls', 'n_lvr_land_c_build.txt', 'n_lvr_land_c_build.csv', 'n_lvr_land_c_build.xml', 'n_lvr_land_c_land.txt', 'n_lvr_land_c_land.csv', 'n_lvr_land_c_land.xml', 'n_lvr_land_c_park.txt', 'n_lvr_land_c_park.csv', 'n_lvr_land_c_park.xml', 'p_lvr_land_a.txt', 'p_lvr_land_a.csv', 'p_lvr_land_a.xml', 'p_lvr_land_a.xls', 'p_lvr_land_a_build.txt', 'p_lvr_land_a_build.csv', 'p_lvr_land_a_build.xml', 'p_lvr_land_a_land.txt', 'p_lvr_land_a_land.csv', 'p_lvr_land_a_land.xml', 'p_lvr_land_a_park.txt', 'p_lvr_land_a_park.csv', 'p_lvr_land_a_park.xml', 'p_lvr_land_b.txt', 'p_lvr_land_b.csv', 'p_lvr_land_b.xml', 'p_lvr_land_b.xls', 'p_lvr_land_b_land.txt', 'p_lvr_land_b_land.csv', 'p_lvr_land_b_land.xml', 'p_lvr_land_b_park.txt', 'p_lvr_land_b_park.csv', 'p_lvr_land_b_park.xml', 'p_lvr_land_c.txt', 'p_lvr_land_c.csv', 'p_lvr_land_c.xml', 'p_lvr_land_c.xls', 'p_lvr_land_c_build.txt', 'p_lvr_land_c_build.csv', 'p_lvr_land_c_build.xml', 'p_lvr_land_c_land.txt', 'p_lvr_land_c_land.csv', 'p_lvr_land_c_land.xml', 'p_lvr_land_c_park.txt', 'p_lvr_land_c_park.csv', 'p_lvr_land_c_park.xml', 'i_lvr_land_a.txt', 'i_lvr_land_a.csv', 'i_lvr_land_a.xml', 'i_lvr_land_a.xls', 'i_lvr_land_a_build.txt', 'i_lvr_land_a_build.csv', 'i_lvr_land_a_build.xml', 'i_lvr_land_a_land.txt', 'i_lvr_land_a_land.csv', 'i_lvr_land_a_land.xml', 'i_lvr_land_a_park.txt', 'i_lvr_land_a_park.csv', 'i_lvr_land_a_park.xml', 'i_lvr_land_b.txt', 'i_lvr_land_b.csv', 'i_lvr_land_b.xml', 'i_lvr_land_b.xls', 'i_lvr_land_b_land.txt', 'i_lvr_land_b_land.csv', 'i_lvr_land_b_land.xml', 'i_lvr_land_b_park.txt', 'i_lvr_land_b_park.csv', 'i_lvr_land_b_park.xml', 'i_lvr_land_c.txt', 'i_lvr_land_c.csv', 'i_lvr_land_c.xml', 'i_lvr_land_c.xls', 'i_lvr_land_c_build.txt', 'i_lvr_land_c_build.csv', 'i_lvr_land_c_build.xml', 'i_lvr_land_c_park.txt', 'i_lvr_land_c_park.csv', 'i_lvr_land_c_park.xml', 'q_lvr_land_a.txt', 'q_lvr_land_a.csv', 'q_lvr_land_a.xml', 'q_lvr_land_a.xls', 'q_lvr_land_a_build.txt', 'q_lvr_land_a_build.csv', 'q_lvr_land_a_build.xml', 'q_lvr_land_a_land.txt', 'q_lvr_land_a_land.csv', 'q_lvr_land_a_land.xml', 'q_lvr_land_a_park.txt', 'q_lvr_land_a_park.csv', 'q_lvr_land_a_park.xml', 'q_lvr_land_b.txt', 'q_lvr_land_b.csv', 'q_lvr_land_b.xml', 'q_lvr_land_b.xls', 'q_lvr_land_b_land.txt', 'q_lvr_land_b_land.csv', 'q_lvr_land_b_land.xml', 'q_lvr_land_b_park.txt', 'q_lvr_land_b_park.csv', 'q_lvr_land_b_park.xml', 'q_lvr_land_c.txt', 'q_lvr_land_c.csv', 'q_lvr_land_c.xml', 'q_lvr_land_c.xls', 'q_lvr_land_c_build.txt', 'q_lvr_land_c_build.csv', 'q_lvr_land_c_build.xml', 'q_lvr_land_c_park.txt', 'q_lvr_land_c_park.csv', 'q_lvr_land_c_park.xml', 'd_lvr_land_a.txt', 'd_lvr_land_a.csv', 'd_lvr_land_a.xml', 'd_lvr_land_a.xls', 'd_lvr_land_a_build.txt', 'd_lvr_land_a_build.csv', 'd_lvr_land_a_build.xml', 'd_lvr_land_a_land.txt', 'd_lvr_land_a_land.csv', 'd_lvr_land_a_land.xml', 'd_lvr_land_a_park.txt', 'd_lvr_land_a_park.csv', 'd_lvr_land_a_park.xml', 'd_lvr_land_b.txt', 'd_lvr_land_b.csv', 'd_lvr_land_b.xml', 'd_lvr_land_b.xls', 'd_lvr_land_b_land.txt', 'd_lvr_land_b_land.csv', 'd_lvr_land_b_land.xml', 'd_lvr_land_b_park.txt', 'd_lvr_land_b_park.csv', 'd_lvr_land_b_park.xml', 'd_lvr_land_c.txt', 'd_lvr_land_c.csv', 'd_lvr_land_c.xml', 'd_lvr_land_c.xls', 'd_lvr_land_c_build.txt', 'd_lvr_land_c_build.csv', 'd_lvr_land_c_build.xml', 'd_lvr_land_c_land.txt', 'd_lvr_land_c_land.csv', 'd_lvr_land_c_land.xml', 'd_lvr_land_c_park.txt', 'd_lvr_land_c_park.csv', 'd_lvr_land_c_park.xml', 'e_lvr_land_a.txt', 'e_lvr_land_a.csv', 'e_lvr_land_a.xml', 'e_lvr_land_a.xls', 'e_lvr_land_a_build.txt', 'e_lvr_land_a_build.csv', 'e_lvr_land_a_build.xml', 'e_lvr_land_a_land.txt', 'e_lvr_land_a_land.csv', 'e_lvr_land_a_land.xml', 'e_lvr_land_a_park.txt', 'e_lvr_land_a_park.csv', 'e_lvr_land_a_park.xml', 'e_lvr_land_b.txt', 'e_lvr_land_b.csv', 'e_lvr_land_b.xml', 'e_lvr_land_b.xls', 'e_lvr_land_b_land.txt', 'e_lvr_land_b_land.csv', 'e_lvr_land_b_land.xml', 'e_lvr_land_b_park.txt', 'e_lvr_land_b_park.csv', 'e_lvr_land_b_park.xml', 'e_lvr_land_c.txt', 'e_lvr_land_c.csv', 'e_lvr_land_c.xml', 'e_lvr_land_c.xls', 'e_lvr_land_c_build.txt', 'e_lvr_land_c_build.csv', 'e_lvr_land_c_build.xml', 'e_lvr_land_c_land.txt', 'e_lvr_land_c_land.csv', 'e_lvr_land_c_land.xml', 'e_lvr_land_c_park.txt', 'e_lvr_land_c_park.csv', 'e_lvr_land_c_park.xml', 't_lvr_land_a.txt', 't_lvr_land_a.csv', 't_lvr_land_a.xml', 't_lvr_land_a.xls', 't_lvr_land_a_build.txt', 't_lvr_land_a_build.csv', 't_lvr_land_a_build.xml', 't_lvr_land_a_land.txt', 't_lvr_land_a_land.csv', 't_lvr_land_a_land.xml', 't_lvr_land_a_park.txt', 't_lvr_land_a_park.csv', 't_lvr_land_a_park.xml', 't_lvr_land_b.txt', 't_lvr_land_b.csv', 't_lvr_land_b.xml', 't_lvr_land_b.xls', 't_lvr_land_b_land.txt', 't_lvr_land_b_land.csv', 't_lvr_land_b_land.xml', 't_lvr_land_b_park.txt', 't_lvr_land_b_park.csv', 't_lvr_land_b_park.xml', 't_lvr_land_c.txt', 't_lvr_land_c.csv', 't_lvr_land_c.xml', 't_lvr_land_c.xls', 't_lvr_land_c_build.txt', 't_lvr_land_c_build.csv', 't_lvr_land_c_build.xml', 't_lvr_land_c_land.txt', 't_lvr_land_c_land.csv', 't_lvr_land_c_land.xml', 'g_lvr_land_a.txt', 'g_lvr_land_a.csv', 'g_lvr_land_a.xml', 'g_lvr_land_a.xls', 'g_lvr_land_a_build.txt', 'g_lvr_land_a_build.csv', 'g_lvr_land_a_build.xml', 'g_lvr_land_a_land.txt', 'g_lvr_land_a_land.csv', 'g_lvr_land_a_land.xml', 'g_lvr_land_a_park.txt', 'g_lvr_land_a_park.csv', 'g_lvr_land_a_park.xml', 'g_lvr_land_b.txt', 'g_lvr_land_b.csv', 'g_lvr_land_b.xml', 'g_lvr_land_b.xls', 'g_lvr_land_b_land.txt', 'g_lvr_land_b_land.csv', 'g_lvr_land_b_land.xml', 'g_lvr_land_b_park.txt', 'g_lvr_land_b_park.csv', 'g_lvr_land_b_park.xml', 'g_lvr_land_c.txt', 'g_lvr_land_c.csv', 'g_lvr_land_c.xml', 'g_lvr_land_c.xls', 'g_lvr_land_c_build.txt', 'g_lvr_land_c_build.csv', 'g_lvr_land_c_build.xml', 'g_lvr_land_c_land.txt', 'g_lvr_land_c_land.csv', 'g_lvr_land_c_land.xml', 'g_lvr_land_c_park.txt', 'g_lvr_land_c_park.csv', 'g_lvr_land_c_park.xml', 'u_lvr_land_a.txt', 'u_lvr_land_a.csv', 'u_lvr_land_a.xml', 'u_lvr_land_a.xls', 'u_lvr_land_a_build.txt', 'u_lvr_land_a_build.csv', 'u_lvr_land_a_build.xml', 'u_lvr_land_a_land.txt', 'u_lvr_land_a_land.csv', 'u_lvr_land_a_land.xml', 'u_lvr_land_a_park.txt', 'u_lvr_land_a_park.csv', 'u_lvr_land_a_park.xml', 'u_lvr_land_b.txt', 'u_lvr_land_b.csv', 'u_lvr_land_b.xml', 'u_lvr_land_b.xls', 'u_lvr_land_b_land.txt', 'u_lvr_land_b_land.csv', 'u_lvr_land_b_land.xml', 'u_lvr_land_b_park.txt', 'u_lvr_land_b_park.csv', 'u_lvr_land_b_park.xml', 'u_lvr_land_c.txt', 'u_lvr_land_c.csv', 'u_lvr_land_c.xml', 'u_lvr_land_c.xls', 'u_lvr_land_c_build.txt', 'u_lvr_land_c_build.csv', 'u_lvr_land_c_build.xml', 'u_lvr_land_c_land.txt', 'u_lvr_land_c_land.csv', 'u_lvr_land_c_land.xml', 'v_lvr_land_a.txt', 'v_lvr_land_a.csv', 'v_lvr_land_a.xml', 'v_lvr_land_a.xls', 'v_lvr_land_a_build.txt', 'v_lvr_land_a_build.csv', 'v_lvr_land_a_build.xml', 'v_lvr_land_a_land.txt', 'v_lvr_land_a_land.csv', 'v_lvr_land_a_land.xml', 'v_lvr_land_a_park.txt', 'v_lvr_land_a_park.csv', 'v_lvr_land_a_park.xml', 'v_lvr_land_b.txt', 'v_lvr_land_b.csv', 'v_lvr_land_b.xml', 'v_lvr_land_b.xls', 'v_lvr_land_b_land.txt', 'v_lvr_land_b_land.csv', 'v_lvr_land_b_land.xml', 'v_lvr_land_b_park.txt', 'v_lvr_land_b_park.csv', 'v_lvr_land_b_park.xml', 'v_lvr_land_c.txt', 'v_lvr_land_c.csv', 'v_lvr_land_c.xml', 'v_lvr_land_c.xls', 'v_lvr_land_c_build.txt', 'v_lvr_land_c_build.csv', 'v_lvr_land_c_build.xml', 'v_lvr_land_c_park.txt', 'v_lvr_land_c_park.csv', 'v_lvr_land_c_park.xml', 'x_lvr_land_a.txt', 'x_lvr_land_a.csv', 'x_lvr_land_a.xml', 'x_lvr_land_a.xls', 'x_lvr_land_a_build.txt', 'x_lvr_land_a_build.csv', 'x_lvr_land_a_build.xml', 'x_lvr_land_a_land.txt', 'x_lvr_land_a_land.csv', 'x_lvr_land_a_land.xml', 'x_lvr_land_c.txt', 'x_lvr_land_c.csv', 'x_lvr_land_c.xml', 'x_lvr_land_c.xls', 'x_lvr_land_c_build.txt', 'x_lvr_land_c_build.csv', 'x_lvr_land_c_build.xml', 'w_lvr_land_a.txt', 'w_lvr_land_a.csv', 'w_lvr_land_a.xml', 'w_lvr_land_a.xls', 'w_lvr_land_a_build.txt', 'w_lvr_land_a_build.csv', 'w_lvr_land_a_build.xml', 'w_lvr_land_a_land.txt', 'w_lvr_land_a_land.csv', 'w_lvr_land_a_land.xml', 'w_lvr_land_a_park.txt', 'w_lvr_land_a_park.csv', 'w_lvr_land_a_park.xml', 'w_lvr_land_c.txt', 'w_lvr_land_c.csv', 'w_lvr_land_c.xml', 'w_lvr_land_c.xls', 'w_lvr_land_c_build.txt', 'w_lvr_land_c_build.csv', 'w_lvr_land_c_build.xml', 'w_lvr_land_c_land.txt', 'w_lvr_land_c_land.csv', 'w_lvr_land_c_land.xml', 'manifest.csv', 'build_time.xml', 'schema-build.csv', 'schema-land.csv', 'schema-main-rent.csv', 'schema-main-sale.csv', 'schema-main.csv', 'schema-park.csv', 'schema-time.csv']

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 661 entries, 0 to 660
Data columns (total 33 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   鄉鎮市區         661 non-null    object
 1   交易標的         661 non-null    object
 2   土地位置建物門牌     661 non-null    object
 3   土地移轉總面積平方公尺  661 non-null    object
 4   都市土地使用分區     621 non-null    object
 5   非都市土地使用分區    1 non-null      object
 6   非都市土地使用編定    1 non-null      object
 7   交易年月日        661 non-null    object
 8   交易筆棟數        661 non-null    object
 9   移轉層次         561 non-null    object
 10  總樓層數         561 non-null    object
 11  建物型態         661 non-null    object
 12  主要用途         547 non-null    object
 13  主要建材         561 non-null    object
 14  建築完成年月       550 non-null    object
 15  建物移轉總面積平方公尺  661 non-null    object
 16  建物現況格局-房     661 non-null    object
 17  建物現況格局-廳     661 non-null    object
 18  建物現況格局-衛     661 non-null    object
 19  建物現況格局-隔間    661 non-null    object
 20  有無管理組織       661 non-null    object
 21  總價元          661 non-null    object
 22  單價元平方公尺      631 non-null    object
 23  車位類別         237 non-null    object
 24  車位移轉總面積平方公尺  661 non-null    object
 25  車位總價元        661 non-null    object
 26  備註           524 non-null    object
 27  編號           661 non-null    object
 28  主建物面積        661 non-null    object
 29  附屬建物面積       661 non-null    object
 30  陽台面積         661 non-null    object
 31  電梯           661 non-null    object
 32  移轉編號         198 non-null    object
dtypes: object(33)
memory usage: 170.5+ KB
None

In [6]:
print(df.head())

                                    鄉鎮市區              交易標的  \
0  The villages and towns urban district  transaction sign
1                                    中山區                車位
2                                    大安區                車位
3                                    大安區                車位
4                                    大安區                土地

                                            土地位置建物門牌  \
0  land sector position building sector house num...
1                                     臺北市中山區林森北路５９２號
2                      臺北市大安區和平東路三段４６４巷２、６、８、１０號地下三層
3                                 臺北市大安區和平東路三段１２３號地下
4                                        學府段三小段401地號

                             土地移轉總面積平方公尺  \
0  land shifting total area square meter
1                                   3.87
2                                   1.76
3                                   1.18
4                                   0.77

                                都市土地使用分區  \
0  the use zoning or compiles and checks
1                                      商
2                                      住
3                                      商
4                                      商

                              非都市土地使用分區                非都市土地使用編定  \
0  the non-metropolis land use district  non-metropolis land use
1                                   NaN                      NaN
2                                   NaN                      NaN
3                                   NaN                      NaN
4                                   NaN                      NaN

                            交易年月日                   交易筆棟數            移轉層次  \
0  transaction year month and day  transaction pen number  shifting level
1                         1141104               土地1建物1車位1              一層
2                         1141104               土地1建物1車位1            地下三層
3                         1141105               土地1建物1車位1         停車場，地下層
4                         1141103               土地1建物0車位0             NaN

                 總樓層數            建物型態      主要用途                     主要建材  \
0  total floor number  building state  main use  main building materials
1                  十層              其他       住家用                   鋼筋混凝土造
2                 十四層              其他      停車空間                 鋼骨鋼筋混凝土造
3                 十二層              其他     見使用執照                   鋼筋混凝土造
4                 NaN              其他       NaN                      NaN

                               建築完成年月                   建物移轉總面積平方公尺  \
0  construction to complete the years  building shifting total area
1                             0560324                         32.62
2                             0910704            42.510000000000005
3                             0691117                         36.17
4                                 NaN                           0.0

                                    建物現況格局-房  \
0  Building present situation pattern - room
1                                          0
2                                          0
3                                          0
4                                          0

                                    建物現況格局-廳  \
0  building present situation pattern - hall
1                                          0
2                                          0
3                                          0
4                                          0

                                      建物現況格局-衛  \
0  building present situation pattern - health
1                                            0
2                                            0
3                                            0
4                                            0

                                           建物現況格局-隔間  \
0  building present situation pattern - compartme...
1                                                  無
2                                                  無
3                                                  無
4                                                  無

                                      有無管理組織              總價元  \
0  Whether there is manages the organization  total price NTD
1                                          有          3000000
2                                          有          2400000
3                                          有          3000000
4                                          無           557736

                               單價元平方公尺                車位類別  \
0  the unit price (NTD / square meter)  the berth category
1                                  NaN                一樓平面
2                                  NaN                坡道平面
3                                  NaN                坡道平面
4                                    0                 NaN

                              車位移轉總面積平方公尺                      車位總價元  \
0  berth shifting total area square meter  the berth total price NTD
1                                   32.62                    3000000
2                                   42.51                    2400000
3                                     0.0                    3000000
4                                     0.0                          0

                      備註                   編號               主建物面積  \
0               the note        serial number  main building area
1                 僅車位交易；  RPRPMLQJJIKGFCA77DA                 0.0
2                 僅車位交易；  RPQNMLRJJIKGFFA87DA                 0.0
3                 僅車位交易；  RPPNMLPJJIKGFFA67EA                 0.0
4  親友、員工、共有人或其他特殊關係間之交易；  RPPNMLRJJIKGFFA87EA                 0.0

                    附屬建物面積          陽台面積        電梯                移轉編號
0  auxiliary building area  balcony area  elevator  transaction number
1                      0.0           0.0         有                 NaN
2                      0.0           0.0         有                 001
3                      0.0           0.0         有                 002
4                      0.0           0.0         無                 003

In [7]:
# remove first row 
df = df.iloc[1:]
df.head(2)

,鄉鎮市區,交易標的,土地位置建物門牌,土地移轉總面積平方公尺,都市土地使用分區,非都市土地使用分區,非都市土地使用編定,交易年月日,交易筆棟數,移轉層次,總樓層數,建物型態,主要用途,主要建材,建築完成年月,建物移轉總面積平方公尺,建物現況格局-房,建物現況格局-廳,建物現況格局-衛,建物現況格局-隔間,有無管理組織,總價元,單價元平方公尺,車位類別,車位移轉總面積平方公尺,車位總價元,備註,編號,主建物面積,附屬建物面積,陽台面積,電梯,移轉編號
1,中山區,車位,臺北市中山區林森北路５９２號,3.87,商,NaN,NaN,1141104,土地1建物1車位1,一層,十層,其他,住家用,鋼筋混凝土造,0560324,32.62,0,0,0,無,有,3000000,NaN,一樓平面,32.62,3000000,僅車位交易；,RPRPMLQJJIKGFCA77DA,0.0,0.0,0.0,有,NaN
2,大安區,車位,臺北市大安區和平東路三段４６４巷２、６、８、１０號地下三層,1.76,住,NaN,NaN,1141104,土地1建物1車位1,地下三層,十四層,其他,停車空間,鋼骨鋼筋混凝土造,0910704,42.510000000000005,0,0,0,無,有,2400000,NaN,坡道平面,42.51,2400000,僅車位交易；,RPQNMLRJJIKGFFA87DA,0.0,0.0,0.0,有,001

In [8]:
df.columns

Index(['鄉鎮市區', '交易標的', '土地位置建物門牌', '土地移轉總面積平方公尺', '都市土地使用分區', '非都市土地使用分區',
       '非都市土地使用編定', '交易年月日', '交易筆棟數', '移轉層次', '總樓層數', '建物型態', '主要用途', '主要建材',
       '建築完成年月', '建物移轉總面積平方公尺', '建物現況格局-房', '建物現況格局-廳', '建物現況格局-衛',
       '建物現況格局-隔間', '有無管理組織', '總價元', '單價元平方公尺', '車位類別', '車位移轉總面積平方公尺', '車位總價元',
       '備註', '編號', '主建物面積', '附屬建物面積', '陽台面積', '電梯', '移轉編號'],
      dtype='object')

In [9]:
df['交易年月日']

1      1141104
2      1141104
3      1141105
4      1141103
5      1141101
        ...
656    1080717
657    1071220
658    1071220
659    1071220
660    1071220
Name: 交易年月日, Length: 660, dtype: object

In [10]:
df['交易年月日'] = df['交易年月日'].str[:3].astype(int).add(1911).astype(str) + df['交易年月日'].str[3:]

In [11]:
df.head(2)

,鄉鎮市區,交易標的,土地位置建物門牌,土地移轉總面積平方公尺,都市土地使用分區,非都市土地使用分區,非都市土地使用編定,交易年月日,交易筆棟數,移轉層次,總樓層數,建物型態,主要用途,主要建材,建築完成年月,建物移轉總面積平方公尺,建物現況格局-房,建物現況格局-廳,建物現況格局-衛,建物現況格局-隔間,有無管理組織,總價元,單價元平方公尺,車位類別,車位移轉總面積平方公尺,車位總價元,備註,編號,主建物面積,附屬建物面積,陽台面積,電梯,移轉編號
1,中山區,車位,臺北市中山區林森北路５９２號,3.87,商,NaN,NaN,20251104,土地1建物1車位1,一層,十層,其他,住家用,鋼筋混凝土造,0560324,32.62,0,0,0,無,有,3000000,NaN,一樓平面,32.62,3000000,僅車位交易；,RPRPMLQJJIKGFCA77DA,0.0,0.0,0.0,有,NaN
2,大安區,車位,臺北市大安區和平東路三段４６４巷２、６、８、１０號地下三層,1.76,住,NaN,NaN,20251104,土地1建物1車位1,地下三層,十四層,其他,停車空間,鋼骨鋼筋混凝土造,0910704,42.510000000000005,0,0,0,無,有,2400000,NaN,坡道平面,42.51,2400000,僅車位交易；,RPQNMLRJJIKGFFA87DA,0.0,0.0,0.0,有,001

In [12]:
df.drop(columns=['都市土地使用分區', '非都市土地使用分區','非都市土地使用編定', '主要建材', 
                 '建物現況格局-房', '建物現況格局-廳', '建物現況格局-衛', '建物現況格局-隔間',
                 '有無管理組織', '車位類別', '車位移轉總面積平方公尺',
                 '編號', '電梯', '移轉編號']).head(5)

,鄉鎮市區,交易標的,土地位置建物門牌,土地移轉總面積平方公尺,交易年月日,交易筆棟數,移轉層次,總樓層數,建物型態,主要用途,建築完成年月,建物移轉總面積平方公尺,總價元,單價元平方公尺,車位總價元,備註,主建物面積,附屬建物面積,陽台面積
1,中山區,車位,臺北市中山區林森北路５９２號,3.87,20251104,土地1建物1車位1,一層,十層,其他,住家用,0560324,32.62,3000000,NaN,3000000,僅車位交易；,0.0,0.0,0.0
2,大安區,車位,臺北市大安區和平東路三段４６４巷２、６、８、１０號地下三層,1.76,20251104,土地1建物1車位1,地下三層,十四層,其他,停車空間,0910704,42.510000000000005,2400000,NaN,2400000,僅車位交易；,0.0,0.0,0.0
3,大安區,車位,臺北市大安區和平東路三段１２３號地下,1.18,20251105,土地1建物1車位1,停車場，地下層,十二層,其他,見使用執照,0691117,36.17,3000000,NaN,3000000,僅車位交易；,0.0,0.0,0.0
4,大安區,土地,學府段三小段401地號,0.77,20251103,土地1建物0車位0,NaN,NaN,其他,NaN,NaN,0.0,557736,0,0,親友、員工、共有人或其他特殊關係間之交易；,0.0,0.0,0.0
5,大安區,車位,臺北市大安區復興南路二段１４８巷３２弄４號地下,4.06,20251101,土地1建物1車位1,地下層,七層,其他,見使用執照,0701214,71.15,3200000,NaN,3200000,親友、員工、共有人或其他特殊關係間之交易；僅車位交易；,0.0,0.0,0.0

In [13]:
test = df.drop(columns=['都市土地使用分區', '非都市土地使用分區','非都市土地使用編定', '主要建材', 
                 '建物現況格局-房', '建物現況格局-廳', '建物現況格局-衛', '建物現況格局-隔間',
                 '有無管理組織', '車位類別', '車位移轉總面積平方公尺',
                 '編號', '電梯', '移轉編號'])

In [14]:
test['交易年月日'] = pd.to_datetime(test['交易年月日'])

In [15]:
test.head(2)

,鄉鎮市區,交易標的,土地位置建物門牌,土地移轉總面積平方公尺,交易年月日,交易筆棟數,移轉層次,總樓層數,建物型態,主要用途,建築完成年月,建物移轉總面積平方公尺,總價元,單價元平方公尺,車位總價元,備註,主建物面積,附屬建物面積,陽台面積
1,中山區,車位,臺北市中山區林森北路５９２號,3.87,2025-11-04,土地1建物1車位1,一層,十層,其他,住家用,0560324,32.62,3000000,NaN,3000000,僅車位交易；,0.0,0.0,0.0
2,大安區,車位,臺北市大安區和平東路三段４６４巷２、６、８、１０號地下三層,1.76,2025-11-04,土地1建物1車位1,地下三層,十四層,其他,停車空間,0910704,42.510000000000005,2400000,NaN,2400000,僅車位交易；,0.0,0.0,0.0

In [16]:
test['總面積(坪)'] = np.round(np.maximum(test['土地移轉總面積平方公尺'].astype(float), test['建物移轉總面積平方公尺'].astype(float)) *  0.3025, 2)

In [17]:
mask = test['建築完成年月'].notna()
test.loc[mask, '建築完成年月'] = test.loc[mask, '建築完成年月'].str[:3].astype(int).add(1911).astype(str) + test.loc[mask, '建築完成年月'].str[3:]
test['建築完成年月'] = pd.to_datetime(test['建築完成年月'])

In [18]:
test[test['鄉鎮市區'] == '士林區'].sort_values(by=['交易年月日'], ascending=False).head(5)

,鄉鎮市區,交易標的,土地位置建物門牌,土地移轉總面積平方公尺,交易年月日,交易筆棟數,移轉層次,總樓層數,建物型態,主要用途,建築完成年月,建物移轉總面積平方公尺,總價元,單價元平方公尺,車位總價元,備註,主建物面積,附屬建物面積,陽台面積,總面積(坪)
25,士林區,土地,溪洲段三小段432地號,12.67,2025-11-13,土地2建物0車位0,NaN,NaN,其他,NaN,NaT,0.0,950000,74980,0,NaN,0.0,0.0,0.0,3.83
42,士林區,土地,三玉段二小段463-1地號,1.39,2025-11-12,土地1建物0車位0,NaN,NaN,其他,NaN,NaT,0.0,300000,215827,0,包含公共設施保留地用地；,0.0,0.0,0.0,0.42
7,士林區,房地(土地+建物),臺北市士林區士商路４０巷１０號,5.81,2025-11-08,土地2建物1車位0,一層,四層,公寓(5樓含以下無電梯),住家用,1979-05-21,17.14,3267500,190636,0,親友、員工、共有人或其他特殊關係間之交易；,13.88,3.25,0.0,5.18
224,士林區,房地(土地+建物),臺北市士林區華齡街３３號四樓,13.41,2025-10-31,土地1建物1車位0,四層,四層,公寓(5樓含以下無電梯),住家用,1973-12-24,38.35,5000000,130378,0,親友、員工、共有人或其他特殊關係間之交易；頂樓加蓋；未登記建物；,35.55,0.0,2.8,11.60
110,士林區,房地(土地+建物)+車位,臺北市士林區承德路四段２巷１７號六樓,28.2,2025-10-31,土地1建物1車位1,六層,十層,華廈(10層含以下有電梯),住家用,2024-07-30,165.21,40100000,242721,0,親友、員工、共有人或其他特殊關係間之交易；受債權債務關係影響或債務抵償；,74.96,0.0,8.1,49.98

In [19]:
test.head(2)

,鄉鎮市區,交易標的,土地位置建物門牌,土地移轉總面積平方公尺,交易年月日,交易筆棟數,移轉層次,總樓層數,建物型態,主要用途,建築完成年月,建物移轉總面積平方公尺,總價元,單價元平方公尺,車位總價元,備註,主建物面積,附屬建物面積,陽台面積,總面積(坪)
1,中山區,車位,臺北市中山區林森北路５９２號,3.87,2025-11-04,土地1建物1車位1,一層,十層,其他,住家用,1967-03-24,32.62,3000000,NaN,3000000,僅車位交易；,0.0,0.0,0.0,9.87
2,大安區,車位,臺北市大安區和平東路三段４６４巷２、６、８、１０號地下三層,1.76,2025-11-04,土地1建物1車位1,地下三層,十四層,其他,停車空間,2002-07-04,42.510000000000005,2400000,NaN,2400000,僅車位交易；,0.0,0.0,0.0,12.86

In [20]:
test['屋齡'] = test.apply(
    lambda row: 
        row['交易年月日'].year - row['建築完成年月'].year
        if (
            pd.notna(row['交易年月日']) and 
            pd.notna(row['建築完成年月']) and 
            (row['交易年月日'].year - row['建築完成年月'].year) > 0
        ) 
        else np.nan
    , axis=1
)

In [21]:
test['樓別/樓高'] = test['移轉層次'] + '/' + test['總樓層數']

In [22]:
test = test.drop(columns=['移轉層次', '總樓層數'])

In [23]:
test[test['鄉鎮市區'] == '士林區'].sort_values(by=['交易年月日'], ascending=False).head(10)

,鄉鎮市區,交易標的,土地位置建物門牌,土地移轉總面積平方公尺,交易年月日,交易筆棟數,建物型態,主要用途,建築完成年月,建物移轉總面積平方公尺,總價元,單價元平方公尺,車位總價元,備註,主建物面積,附屬建物面積,陽台面積,總面積(坪),屋齡,樓別/樓高
25,士林區,土地,溪洲段三小段432地號,12.67,2025-11-13,土地2建物0車位0,其他,NaN,NaT,0.0,950000,74980,0,NaN,0.0,0.0,0.0,3.83,NaN,NaN
42,士林區,土地,三玉段二小段463-1地號,1.39,2025-11-12,土地1建物0車位0,其他,NaN,NaT,0.0,300000,215827,0,包含公共設施保留地用地；,0.0,0.0,0.0,0.42,NaN,NaN
7,士林區,房地(土地+建物),臺北市士林區士商路４０巷１０號,5.81,2025-11-08,土地2建物1車位0,公寓(5樓含以下無電梯),住家用,1979-05-21,17.14,3267500,190636,0,親友、員工、共有人或其他特殊關係間之交易；,13.88,3.25,0.0,5.18,46.0,一層/四層
224,士林區,房地(土地+建物),臺北市士林區華齡街３３號四樓,13.41,2025-10-31,土地1建物1車位0,公寓(5樓含以下無電梯),住家用,1973-12-24,38.35,5000000,130378,0,親友、員工、共有人或其他特殊關係間之交易；頂樓加蓋；未登記建物；,35.55,0.0,2.8,11.60,52.0,四層/四層
110,士林區,房地(土地+建物)+車位,臺北市士林區承德路四段２巷１７號六樓,28.2,2025-10-31,土地1建物1車位1,華廈(10層含以下有電梯),住家用,2024-07-30,165.21,40100000,242721,0,親友、員工、共有人或其他特殊關係間之交易；受債權債務關係影響或債務抵償；,74.96,0.0,8.1,49.98,1.0,六層/十層
186,士林區,房地(土地+建物)+車位,臺北市士林區天母北路８７巷２弄１２號二樓,3.6,2025-10-31,土地1建物1車位1,華廈(10層含以下有電梯),住家用,1984-05-08,20.0,3330000,166500,0,陽台加窗親友、員工、共有人或其他特殊關係間之交易；陽台外推；其他增建；,15.1,0.0,2.84,6.05,41.0,二層/七層
159,士林區,房地(土地+建物),臺北市士林區中正路３６６號,43.67,2025-10-30,土地1建物1車位0,透天厝,住家用,1967-11-17,102.79,22330000,217239,0,地清或未辦繼承標售；,102.79,0.0,0.0,31.09,58.0,全/三層
143,士林區,房地(土地+建物),臺北市士林區延平北路五段５０號十樓,22.91,2025-10-29,土地2建物1車位0,住宅大樓(11層含以上有電梯),住家用,2013-03-12,143.46,28200000,196570,0,其他增建:機房其他增建；,85.25,4.06,6.64,43.40,12.0,十層/十三層
181,士林區,土地,溪洲段三小段219地號,1227.0,2025-10-27,土地1建物0車位0,其他,NaN,NaT,0.0,117880000,96072,0,包含公共設施保留地用地；,0.0,0.0,0.0,371.17,NaN,NaN
158,士林區,土地,溪洲段二小段176地號,61.54,2025-10-27,土地15建物0車位0,其他,NaN,NaT,0.0,4600000,74748,0,NaN,0.0,0.0,0.0,18.62,NaN,NaN

In [24]:
simple = test.drop(columns=['交易標的', '土地移轉總面積平方公尺', '交易筆棟數', '建築完成年月', 
                            '建物移轉總面積平方公尺', '車位總價元', '備註', '主建物面積',
                            '附屬建物面積', '陽台面積'])

In [25]:
simple.head(5)

,鄉鎮市區,土地位置建物門牌,交易年月日,建物型態,主要用途,總價元,單價元平方公尺,總面積(坪),屋齡,樓別/樓高
1,中山區,臺北市中山區林森北路５９２號,2025-11-04,其他,住家用,3000000,NaN,9.87,58.0,一層/十層
2,大安區,臺北市大安區和平東路三段４６４巷２、６、８、１０號地下三層,2025-11-04,其他,停車空間,2400000,NaN,12.86,23.0,地下三層/十四層
3,大安區,臺北市大安區和平東路三段１２３號地下,2025-11-05,其他,見使用執照,3000000,NaN,10.94,45.0,停車場，地下層/十二層
4,大安區,學府段三小段401地號,2025-11-03,其他,NaN,557736,0,0.23,NaN,NaN
5,大安區,臺北市大安區復興南路二段１４８巷３２弄４號地下,2025-11-01,其他,見使用執照,3200000,NaN,21.52,44.0,地下層/七層

In [25]:
from sqlalchemy import create_engine, text

In [26]:
# credentials
username = 'postgres'
password = '1234'
host = 'localhost'
port = '5432'
database = 'test_db'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

In [27]:
# test connection
with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone())

('PostgreSQL 18.0 on x86_64-windows, compiled by msvc-19.44.35217, 64-bit',)

In [30]:
test.shape

(440, 20)

In [28]:
simple.to_sql('test1', engine, if_exists='replace', index=False)

440

In [29]:
pd.read_sql("SELECT * FROM test1;", engine)

,鄉鎮市區,土地位置建物門牌,交易年月日,建物型態,主要用途,總價元,單價元平方公尺,總面積(坪),屋齡,樓別/樓高
0,松山區,臺北市松山區南京東路三段２５６巷４６號地下層,2025-10-02,其他,見使用執照,2500000,None,10.11,41.0,地下層/六層
1,松山區,延吉段三小段404地號,2025-10-02,其他,None,2280000,57000,12.10,NaN,None
2,萬華區,青年段一小段690地號,2025-10-02,其他,None,606,0,0.01,NaN,None
3,北投區,行義段三小段522地號,2025-10-02,其他,None,150000,0,0.20,NaN,None
4,松山區,臺北市松山區南京東路四段５３巷１１弄９號二樓,2025-10-02,公寓(5樓含以下無電梯),住家用,26500000,230736,34.74,53.0,二層，陽臺/四層
...,...,...,...,...,...,...,...,...,...,...
435,中正區,臺北市中正區三元街８５號四樓之１,2019-10-15,住宅大樓(11層含以上有電梯),住家用,21798738,239136,35.66,NaN,四層/二十一層
436,中正區,臺北市中正區三元街８５號四樓之５,2019-09-29,住宅大樓(11層含以上有電梯),住家用,20720000,241887,25.91,NaN,四層/二十一層
437,中正區,臺北市中正區三元街８５號四樓之６,2019-08-05,住宅大樓(11層含以上有電梯),住家用,38660000,230306,58.36,NaN,四層/二十一層
438,中正區,臺北市中正區三元街８５號六樓之５,2019-08-02,住宅大樓(11層含以上有電梯),住家用,20600000,240486,25.91,NaN,六層/二十一層
439,中正區,臺北市中正區三元街８５號二十樓之１,2019-07-29,住宅大樓(11層含以上有電梯),住家用,24980000,278250,35.67,NaN,二十層/二十一層